### PR TITLE
Add Laravel 8 support 

### PR DESCRIPTION
**Pull request by WilburJZHAO**
Add Laravel 8 support

### CODE REVIEW

**Comment by antonkomarev** [comment]
@WilburJZHAO thank you for the contribution! Could you add changes to .travis.yml as well? Here is example how I added PHP8 support to another one package: https://github.com/cybercog/laravel-love/commit/0a8820e732e6aefaefc0b970c1ea7c82b7ad4f37

**Comment by antonkomarev** [comment]
@WilburJZHAO sorry, I was too tired when I wrote that comment and gave a link on a wrong commit. There is no need to add PHP8 support to add Laravel 8 support. My bad.

**Comment by WilburJZHAO** [comment]
@antonkomarev All good, I just took out the PHP 8 support.

**Comment by antonkomarev** [comment]
I'm away from my computer, so cannot make a release. Will do it on the next week.

**Comment by antonkomarev** [comment]
@WilburJZHAO sorry for long wait time, but adding new Laravel versions required more than just adding them in composer.json: #23 

[Laravel Ownership v5.3.0](https://github.com/cybercog/laravel-ownership/releases/tag/5.3.0) has been released with Laravel 6.x, 7.x, 8.x support and PHP8 support.

**Comment by WilburJZHAO** [comment]
@antonkomarev Thank you!

**Pull request merged**
